import type { Card } from "../../types/card";

/** cards that aren't derived from a Pokemon move: basic strikes/defends, draw, energy, orb utility */
export const HAND_AUTHORED_CARDS: Card[] = [
  // shared basics (every class starts with a few of these)
  {
    id: "basic-strike",
    sourceMoveId: null,
    name: "basic-strike",
    koreanName: "기본 타격",
    cost: 1,
    category: "attack",
    classId: "warrior",
    exhaust: false,
    moveType: "normal",
    effects: [{ kind: "damage", power: 40, moveType: "normal", critRate: 0, minHits: null, maxHits: null }],
  },
  {
    id: "basic-guard",
    sourceMoveId: null,
    name: "basic-guard",
    koreanName: "기본 방어",
    cost: 1,
    category: "skill",
    classId: "warrior",
    exhaust: false,
    moveType: null,
    effects: [{ kind: "block", amount: 5 }],
  },
  {
    id: "quick-scout",
    sourceMoveId: null,
    name: "quick-scout",
    koreanName: "정찰",
    cost: 1,
    category: "skill",
    classId: "warrior",
    exhaust: false,
    moveType: null,
    effects: [{ kind: "draw", count: 2 }],
  },
  {
    id: "deep-breath",
    sourceMoveId: null,
    name: "deep-breath",
    koreanName: "심호흡",
    cost: 0,
    category: "skill",
    classId: "warrior",
    exhaust: true,
    moveType: null,
    effects: [{ kind: "energyGain", amount: 2 }],
  },
  // mage orb utility
  {
    id: "channel-fire",
    sourceMoveId: null,
    name: "channel-fire",
    koreanName: "불꽃 오브 충전",
    cost: 1,
    category: "skill",
    classId: "mage",
    exhaust: false,
    moveType: "fire",
    effects: [{ kind: "channelOrb", orbType: "fire" }],
  },
  {
    id: "channel-water",
    sourceMoveId: null,
    name: "channel-water",
    koreanName: "물 오브 충전",
    cost: 1,
    category: "skill",
    classId: "mage",
    exhaust: false,
    moveType: "water",
    effects: [{ kind: "channelOrb", orbType: "water" }],
  },
  {
    id: "channel-electric",
    sourceMoveId: null,
    name: "channel-electric",
    koreanName: "전기 오브 충전",
    cost: 1,
    category: "skill",
    classId: "mage",
    exhaust: false,
    moveType: "electric",
    effects: [{ kind: "channelOrb", orbType: "electric" }],
  },
  {
    id: "channel-psychic",
    sourceMoveId: null,
    name: "channel-psychic",
    koreanName: "에스퍼 오브 충전",
    cost: 1,
    category: "skill",
    classId: "mage",
    exhaust: false,
    moveType: "psychic",
    effects: [{ kind: "channelOrb", orbType: "psychic" }],
  },
  {
    id: "evoke-front",
    sourceMoveId: null,
    name: "evoke-front",
    koreanName: "오브 발동",
    cost: 0,
    category: "skill",
    classId: "mage",
    exhaust: true,
    moveType: null,
    effects: [{ kind: "evokeOrb" }],
  },
];

export function getHandAuthoredCard(id: string): Card {
  const card = HAND_AUTHORED_CARDS.find((c) => c.id === id);
  if (!card) throw new Error(`Unknown hand-authored card: ${id}`);
  return card;
}
